apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-java
spec:
  selector:
    matchLabels:
      app: sample-java
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-java
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - name: app
        image: ghcr.io/pavolloffay/spring-petclinic:latest
